name: Run Supabase Script

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install supabase-py
      - name: Run script
        run: python billupdate.py